.TH FDMDV_GET_TEST_BITS 1 2020-12-04 fdmdv_get_test_bits "User commands"
.SH NAME
fdmdv_get_test_bits \- a diagnostic tool for the codec2 library to generate data for fdmdv_mod.
.SH SYNOPSIS
.B fdmdv_get_test_bits usage:
.IR OutputBitFile
.IR numBits
.IR [Nc]
.PP
.SH DESCRIPTION
.PP
Generates a file of packed test bits, useful for input to fdmdv_mod.
.PP
.SH EXAMPLE
 fdmdv_get_test_bits test.c2 1400
.PP
.SH OPTIONS
The first argument, 
.IR OutputBitFile
is the file name of a file to be created with test sample data. If "-" is
given the output is sent to stdout.
.PP
The second argument, 
.IR numBits
is an integer number of bits per second to use.
.PP
The optional third argument,
.IR [Nc]
is the number of carriers to use in the modem. The default is 14.
The minimum is 2 and the maximum is 20.
.PP
.SH "SEE ALSO"
.BR fdmdv_mod (1),
.BR fdmdv_demod (1)
.BR fdmdv_put_test_bits (1)
